# screen constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_CENTER = (SCREEN_WIDTH/2 , SCREEN_HEIGHT/2)

# drawing constants
LINE_WIDTH = 2

# bullet constants
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN_SECONDS = 0.3

# player constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# asteroid constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS